var child = [
  { 'dupe': false, 'type': 4, 'name': 'icons', 'dir': 'c0', 'linked': 2, 'url': 'http://127.0.0.1/icons/', 'fetched': true, 'code': 403, 'len': 290, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': true, 'child_cnt': 30, 'issue_cnt': [ 3, 0, 0, 0, 0 ], 'sig': 0x272ba8aa },
  { 'dupe': false, 'type': 8, 'name': 'faker.js', 'dir': 'c1', 'linked': 2, 'url': 'http://127.0.0.1/faker.js', 'fetched': true, 'code': 200, 'len': 1358, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'LoginStylesheet.css', 'dir': 'c2', 'linked': 2, 'url': 'http://127.0.0.1/LoginStylesheet.css', 'fetched': true, 'code': 200, 'len': 754, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'script.js', 'dir': 'c3', 'linked': 2, 'url': 'http://127.0.0.1/script.js', 'fetched': true, 'code': 200, 'len': 1214, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'styles.css', 'dir': 'c4', 'linked': 2, 'url': 'http://127.0.0.1/styles.css', 'fetched': true, 'code': 200, 'len': 1424, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'sync.png', 'dir': 'c5', 'linked': 2, 'url': 'http://127.0.0.1/sync.png', 'fetched': true, 'code': 200, 'len': 9719, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'test.sql', 'dir': 'c7', 'linked': 2, 'url': 'http://127.0.0.1/test.sql', 'fetched': true, 'code': 200, 'len': 2281, 'decl_mime': 'application/x-sql', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 16, 'name': 'history.php', 'dir': 'c8', 'linked': 2, 'url': 'http://127.0.0.1/history.php', 'fetched': true, 'code': 200, 'len': 1312, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'login.php', 'dir': 'c9', 'linked': 5, 'url': 'http://127.0.0.1/login.php', 'fetched': true, 'code': 200, 'len': 1139, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0xe729e6d8 },
  { 'dupe': false, 'type': 16, 'name': 'login_kopia.php', 'dir': 'c10', 'linked': 2, 'url': 'http://127.0.0.1/login_kopia.php', 'fetched': true, 'code': 200, 'len': 1085, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffeed694 },
  { 'dupe': false, 'type': 16, 'name': 'main.php', 'dir': 'c11', 'linked': 2, 'url': 'http://127.0.0.1/main.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'transfer.php', 'dir': 'c12', 'linked': 2, 'url': 'http://127.0.0.1/transfer.php', 'fetched': true, 'code': 200, 'len': 26, 'decl_mime': 'text/html', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xf7acc54b },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c13', 'linked': 2, 'url': 'http://127.0.0.1/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2967, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c14', 'linked': 2, 'url': 'http://127.0.0.1/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2967, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
